---
- name: Install MariaDB
  hosts: database
  become: yes
  tasks:
  - name: Install MariaDB and python3-PyMySQL
    package:
     name: "{{ item }}"
     state: latest
    loop:
    - mariadb-server
    - python3-PyMySQL
    when: 
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
  - name: Start MariaDB Service
    service:
      name: mariadb
      state: started
      enabled: true
    notify: set the db root password

  handlers:
    - name: set the db root password
      mysql_user:
        name: root
        password: "{{ db_root_pass }}"
...
